<?php
/**
 * CompletionResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class CompletionResponse implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $id = null;
    #[Description('')]
    protected ?string $object = null;
    #[Description('')]
    protected ?int $created = null;
    #[Description('')]
    protected ?string $model = null;
    /**
     * @var array<CompletionChoice>|null
     */
    #[Description('')]
    protected ?array $choices = null;
    #[Description('')]
    protected ?CompletionUsage $usage = null;
    #[Key('service_tier')]
    #[Description('')]
    protected ?string $serviceTier = null;
    #[Key('system_fingerprint')]
    #[Description('')]
    protected ?string $systemFingerprint = null;
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setObject(?string $object): void
    {
        $this->object = $object;
    }
    public function getObject(): ?string
    {
        return $this->object;
    }
    public function setCreated(?int $created): void
    {
        $this->created = $created;
    }
    public function getCreated(): ?int
    {
        return $this->created;
    }
    public function setModel(?string $model): void
    {
        $this->model = $model;
    }
    public function getModel(): ?string
    {
        return $this->model;
    }
    /**
     * @param array<CompletionChoice>|null $choices
     */
    public function setChoices(?array $choices): void
    {
        $this->choices = $choices;
    }
    /**
     * @return array<CompletionChoice>|null
     */
    public function getChoices(): ?array
    {
        return $this->choices;
    }
    public function setUsage(?CompletionUsage $usage): void
    {
        $this->usage = $usage;
    }
    public function getUsage(): ?CompletionUsage
    {
        return $this->usage;
    }
    public function setServiceTier(?string $serviceTier): void
    {
        $this->serviceTier = $serviceTier;
    }
    public function getServiceTier(): ?string
    {
        return $this->serviceTier;
    }
    public function setSystemFingerprint(?string $systemFingerprint): void
    {
        $this->systemFingerprint = $systemFingerprint;
    }
    public function getSystemFingerprint(): ?string
    {
        return $this->systemFingerprint;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('object', $this->object);
        $record->put('created', $this->created);
        $record->put('model', $this->model);
        $record->put('choices', $this->choices);
        $record->put('usage', $this->usage);
        $record->put('service_tier', $this->serviceTier);
        $record->put('system_fingerprint', $this->systemFingerprint);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
