<?php
/**
 * CompletionUsage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class CompletionUsage implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('completion_tokens')]
    #[Description('')]
    protected ?int $completionTokens = null;
    #[Key('prompt_tokens')]
    #[Description('')]
    protected ?int $promptTokens = null;
    #[Key('total_tokens')]
    #[Description('')]
    protected ?int $totalTokens = null;
    #[Key('completion_tokens_details')]
    #[Description('')]
    protected ?CompletionTokensDetails $completionTokensDetails = null;
    #[Key('prompt_tokens_details')]
    #[Description('')]
    protected ?PromptTokensDetails $promptTokensDetails = null;
    public function setCompletionTokens(?int $completionTokens): void
    {
        $this->completionTokens = $completionTokens;
    }
    public function getCompletionTokens(): ?int
    {
        return $this->completionTokens;
    }
    public function setPromptTokens(?int $promptTokens): void
    {
        $this->promptTokens = $promptTokens;
    }
    public function getPromptTokens(): ?int
    {
        return $this->promptTokens;
    }
    public function setTotalTokens(?int $totalTokens): void
    {
        $this->totalTokens = $totalTokens;
    }
    public function getTotalTokens(): ?int
    {
        return $this->totalTokens;
    }
    public function setCompletionTokensDetails(?CompletionTokensDetails $completionTokensDetails): void
    {
        $this->completionTokensDetails = $completionTokensDetails;
    }
    public function getCompletionTokensDetails(): ?CompletionTokensDetails
    {
        return $this->completionTokensDetails;
    }
    public function setPromptTokensDetails(?PromptTokensDetails $promptTokensDetails): void
    {
        $this->promptTokensDetails = $promptTokensDetails;
    }
    public function getPromptTokensDetails(): ?PromptTokensDetails
    {
        return $this->promptTokensDetails;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('completion_tokens', $this->completionTokens);
        $record->put('prompt_tokens', $this->promptTokens);
        $record->put('total_tokens', $this->totalTokens);
        $record->put('completion_tokens_details', $this->completionTokensDetails);
        $record->put('prompt_tokens_details', $this->promptTokensDetails);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
