<?php
/**
 * CompletionMessageAssistant automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class CompletionMessageAssistant extends CompletionMessage implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $audio = null;
    #[Description('')]
    protected ?string $name = null;
    #[Description('')]
    protected ?string $refusal = null;
    /**
     * @var array<string>|null
     */
    #[Key('tool_calls')]
    #[Description('')]
    protected ?array $toolCalls = null;
    public function setAudio(?string $audio): void
    {
        $this->audio = $audio;
    }
    public function getAudio(): ?string
    {
        return $this->audio;
    }
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setRefusal(?string $refusal): void
    {
        $this->refusal = $refusal;
    }
    public function getRefusal(): ?string
    {
        return $this->refusal;
    }
    /**
     * @param array<string>|null $toolCalls
     */
    public function setToolCalls(?array $toolCalls): void
    {
        $this->toolCalls = $toolCalls;
    }
    /**
     * @return array<string>|null
     */
    public function getToolCalls(): ?array
    {
        return $this->toolCalls;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('audio', $this->audio);
        $record->put('name', $this->name);
        $record->put('refusal', $this->refusal);
        $record->put('tool_calls', $this->toolCalls);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
