<?php
/**
 * CompletionChoice automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class CompletionChoice implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?int $index = null;
    #[Description('')]
    protected ?CompletionMessage $message = null;
    #[Key('finish_reason')]
    #[Description('')]
    protected ?string $finishReason = null;
    public function setIndex(?int $index): void
    {
        $this->index = $index;
    }
    public function getIndex(): ?int
    {
        return $this->index;
    }
    public function setMessage(?CompletionMessage $message): void
    {
        $this->message = $message;
    }
    public function getMessage(): ?CompletionMessage
    {
        return $this->message;
    }
    public function setFinishReason(?string $finishReason): void
    {
        $this->finishReason = $finishReason;
    }
    public function getFinishReason(): ?string
    {
        return $this->finishReason;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('index', $this->index);
        $record->put('message', $this->message);
        $record->put('finish_reason', $this->finishReason);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
