<?php
/**
 * CompletionMessageTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class CompletionMessageTool extends CompletionMessage implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('tool_call_id')]
    #[Description('')]
    protected ?string $toolCallId = null;
    public function setToolCallId(?string $toolCallId): void
    {
        $this->toolCallId = $toolCallId;
    }
    public function getToolCallId(): ?string
    {
        return $this->toolCallId;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('tool_call_id', $this->toolCallId);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
