<?php
/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Error implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?ErrorDetail $error = null;
    public function setError(?ErrorDetail $error): void
    {
        $this->error = $error;
    }
    public function getError(): ?ErrorDetail
    {
        return $this->error;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('error', $this->error);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
