<?php
/**
 * PromptTokensDetails automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class PromptTokensDetails implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('audio_tokens')]
    #[Description('')]
    protected ?int $audioTokens = null;
    #[Key('cached_tokens')]
    #[Description('')]
    protected ?int $cachedTokens = null;
    public function setAudioTokens(?int $audioTokens): void
    {
        $this->audioTokens = $audioTokens;
    }
    public function getAudioTokens(): ?int
    {
        return $this->audioTokens;
    }
    public function setCachedTokens(?int $cachedTokens): void
    {
        $this->cachedTokens = $cachedTokens;
    }
    public function getCachedTokens(): ?int
    {
        return $this->cachedTokens;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('audio_tokens', $this->audioTokens);
        $record->put('cached_tokens', $this->cachedTokens);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
