<?php
/**
 * ResponseTextFormatJsonSchema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseTextFormatJsonSchema extends ResponseTextFormat implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.')]
    protected ?string $name = null;
    #[Description('The schema for the response format, described as a JSON Schema object.')]
    protected mixed $schema = null;
    #[Description('The type of response format being defined. Always json_schema.')]
    #[Nullable(true)]
    protected ?string $type = 'json_schema';
    #[Description('A description of what the response format is for, used by the model to determine how to respond in the format.')]
    protected ?string $description = null;
    #[Description('Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the schema field. Only a subset of JSON Schema is supported when strict is true.')]
    protected ?bool $strict = null;
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setSchema(mixed $schema): void
    {
        $this->schema = $schema;
    }
    public function getSchema(): mixed
    {
        return $this->schema;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function setStrict(?bool $strict): void
    {
        $this->strict = $strict;
    }
    public function getStrict(): ?bool
    {
        return $this->strict;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('name', $this->name);
        $record->put('schema', $this->schema);
        $record->put('type', $this->type);
        $record->put('description', $this->description);
        $record->put('strict', $this->strict);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
