<?php
/**
 * ResponseResponseOutputFunctionCall automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseResponseOutputFunctionCall implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('A JSON string of the arguments to pass to the function.')]
    #[Nullable(true)]
    protected ?string $arguments = null;
    #[Key('call_id')]
    #[Description('The unique ID of the function tool call generated by the model.')]
    #[Nullable(true)]
    protected ?string $callId = null;
    #[Description('The name of the function to run.')]
    #[Nullable(true)]
    protected ?string $name = null;
    #[Description('The type of the function tool call. Always function_call.')]
    #[Nullable(true)]
    protected ?string $type = 'function_call';
    #[Description('The unique ID of the function tool call.')]
    #[Nullable(true)]
    protected ?string $id = null;
    #[Description('The status of the item. One of in_progress, completed, or incomplete. Populated when items are returned via API.')]
    #[Nullable(true)]
    protected ?string $status = null;
    public function setArguments(?string $arguments): void
    {
        $this->arguments = $arguments;
    }
    public function getArguments(): ?string
    {
        return $this->arguments;
    }
    public function setCallId(?string $callId): void
    {
        $this->callId = $callId;
    }
    public function getCallId(): ?string
    {
        return $this->callId;
    }
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }
    public function getStatus(): ?string
    {
        return $this->status;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('arguments', $this->arguments);
        $record->put('call_id', $this->callId);
        $record->put('name', $this->name);
        $record->put('type', $this->type);
        $record->put('id', $this->id);
        $record->put('status', $this->status);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
