<?php
/**
 * ResponseResponseOutputMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Nullable;

#[Description('An output message from the model.')]
class ResponseResponseOutputMessage extends ResponseResponseOutput implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<string>|null
     */
    #[Description('The content of the output message.')]
    protected ?array $content = null;
    #[Description('The unique ID of the output message.')]
    protected ?string $id = null;
    #[Description('The role of the output message. Always assistant.')]
    protected ?string $role = null;
    #[Description('The status of the message input. One of in_progress, completed, or incomplete. Populated when input items are returned via API.')]
    protected ?string $status = null;
    #[Description('The type of the output message. Always message.')]
    #[Nullable(true)]
    protected ?string $type = 'message';
    /**
     * @param array<string>|null $content
     */
    public function setContent(?array $content): void
    {
        $this->content = $content;
    }
    /**
     * @return array<string>|null
     */
    public function getContent(): ?array
    {
        return $this->content;
    }
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setRole(?string $role): void
    {
        $this->role = $role;
    }
    public function getRole(): ?string
    {
        return $this->role;
    }
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }
    public function getStatus(): ?string
    {
        return $this->status;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('content', $this->content);
        $record->put('id', $this->id);
        $record->put('role', $this->role);
        $record->put('status', $this->status);
        $record->put('type', $this->type);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
