<?php
/**
 * ResponseToolFunction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ResponseToolFunction extends ResponseTool implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The name of the function to call.')]
    protected ?string $name = null;
    #[Description('A JSON schema object describing the parameters of the function.')]
    protected mixed $parameters = null;
    #[Description('Whether to enforce strict parameter validation. Default true.')]
    protected ?bool $strict = null;
    #[Description('The type of the function tool. Always function.')]
    protected ?string $type = null;
    #[Description('A description of the function. Used by the model to determine whether or not to call the function.')]
    protected ?string $description = null;
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setParameters(mixed $parameters): void
    {
        $this->parameters = $parameters;
    }
    public function getParameters(): mixed
    {
        return $this->parameters;
    }
    public function setStrict(?bool $strict): void
    {
        $this->strict = $strict;
    }
    public function getStrict(): ?bool
    {
        return $this->strict;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('name', $this->name);
        $record->put('parameters', $this->parameters);
        $record->put('strict', $this->strict);
        $record->put('type', $this->type);
        $record->put('description', $this->description);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
