<?php
/**
 * ResponseRequestText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseRequestText implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('An object specifying the format that the model must output.')]
    #[Nullable(true)]
    protected ?ResponseRequestTextFormat $format = null;
    #[Description('Constrains the verbosity of the model\'s response. Lower values will result in more concise responses, while higher values will result in more verbose responses. Currently supported values are low, medium, and high.')]
    #[Nullable(true)]
    protected ?string $verbosity = null;
    public function setFormat(?ResponseRequestTextFormat $format): void
    {
        $this->format = $format;
    }
    public function getFormat(): ?ResponseRequestTextFormat
    {
        return $this->format;
    }
    public function setVerbosity(?string $verbosity): void
    {
        $this->verbosity = $verbosity;
    }
    public function getVerbosity(): ?string
    {
        return $this->verbosity;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('format', $this->format);
        $record->put('verbosity', $this->verbosity);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
