<?php
/**
 * ResponseToolWebSearchFilter automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class ResponseToolWebSearchFilter implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<string>|null
     */
    #[Key('allowed_domains')]
    #[Description('Allowed domains for the search. If not provided, all domains are allowed. Subdomains of the provided domains are allowed as well.')]
    protected ?array $allowedDomains = null;
    /**
     * @param array<string>|null $allowedDomains
     */
    public function setAllowedDomains(?array $allowedDomains): void
    {
        $this->allowedDomains = $allowedDomains;
    }
    /**
     * @return array<string>|null
     */
    public function getAllowedDomains(): ?array
    {
        return $this->allowedDomains;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('allowed_domains', $this->allowedDomains);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
