<?php
/**
 * ResponseResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class ResponseResponse implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('created_at')]
    #[Description('Unix timestamp (in seconds) of when this Response was created.')]
    protected ?int $createdAt = null;
    #[Description('An error object returned when the model fails to generate a Response.')]
    protected ?ResponseResponseError $error = null;
    #[Description('Unique identifier for this Response.')]
    protected ?string $id = null;
    #[Key('incomplete_details')]
    #[Description('Details about why the response is incomplete.')]
    protected ?string $incompleteDetails = null;
    #[Description('The object type of this resource - always set to response.')]
    protected ?string $object = null;
    /**
     * @var array<ResponseResponseOutput>|null
     */
    #[Description('An array of content items generated by the model.')]
    protected ?array $output = null;
    public function setCreatedAt(?int $createdAt): void
    {
        $this->createdAt = $createdAt;
    }
    public function getCreatedAt(): ?int
    {
        return $this->createdAt;
    }
    public function setError(?ResponseResponseError $error): void
    {
        $this->error = $error;
    }
    public function getError(): ?ResponseResponseError
    {
        return $this->error;
    }
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setIncompleteDetails(?string $incompleteDetails): void
    {
        $this->incompleteDetails = $incompleteDetails;
    }
    public function getIncompleteDetails(): ?string
    {
        return $this->incompleteDetails;
    }
    public function setObject(?string $object): void
    {
        $this->object = $object;
    }
    public function getObject(): ?string
    {
        return $this->object;
    }
    /**
     * @param array<ResponseResponseOutput>|null $output
     */
    public function setOutput(?array $output): void
    {
        $this->output = $output;
    }
    /**
     * @return array<ResponseResponseOutput>|null
     */
    public function getOutput(): ?array
    {
        return $this->output;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('created_at', $this->createdAt);
        $record->put('error', $this->error);
        $record->put('id', $this->id);
        $record->put('incomplete_details', $this->incompleteDetails);
        $record->put('object', $this->object);
        $record->put('output', $this->output);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
