<?php
/**
 * ResponseToolMCP automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;

#[Description('')]
class ResponseToolMCP extends ResponseTool implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('server_label')]
    #[Description('A label for this MCP server, used to identify it in tool calls.')]
    protected ?string $serverLabel = null;
    #[Description('The type of the MCP tool. Always mcp.')]
    protected ?string $type = null;
    /**
     * @var array<string>|null
     */
    #[Key('allowed_tools')]
    #[Description('List of allowed tool names or a filter object.')]
    protected ?array $allowedTools = null;
    #[Description('An OAuth access token that can be used with a remote MCP server, either with a custom MCP server URL or a service connector. Your application must handle the OAuth authorization flow and provide the token here.')]
    protected ?string $authorization = null;
    #[Key('connector_id')]
    #[Description('Identifier for service connectors, like those available in ChatGPT. One of server_url or connector_id must be provided.')]
    protected ?string $connectorId = null;
    /**
     * @var \PSX\Record\Record<string>|null
     */
    #[Description('Optional HTTP headers to send to the MCP server. Use for authentication or other purposes.')]
    protected ?\PSX\Record\Record $headers = null;
    #[Key('require_approval')]
    #[Description('Specify which of the MCP server\'s tools require approval.')]
    protected ?string $requireApproval = null;
    #[Key('server_description')]
    #[Description('Optional description of the MCP server, used to provide more context.')]
    protected ?string $serverDescription = null;
    #[Key('server_url')]
    #[Description('The URL for the MCP server. One of server_url or connector_id must be provided.')]
    protected ?string $serverUrl = null;
    public function setServerLabel(?string $serverLabel): void
    {
        $this->serverLabel = $serverLabel;
    }
    public function getServerLabel(): ?string
    {
        return $this->serverLabel;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    /**
     * @param array<string>|null $allowedTools
     */
    public function setAllowedTools(?array $allowedTools): void
    {
        $this->allowedTools = $allowedTools;
    }
    /**
     * @return array<string>|null
     */
    public function getAllowedTools(): ?array
    {
        return $this->allowedTools;
    }
    public function setAuthorization(?string $authorization): void
    {
        $this->authorization = $authorization;
    }
    public function getAuthorization(): ?string
    {
        return $this->authorization;
    }
    public function setConnectorId(?string $connectorId): void
    {
        $this->connectorId = $connectorId;
    }
    public function getConnectorId(): ?string
    {
        return $this->connectorId;
    }
    /**
     * @param \PSX\Record\Record<string>|null $headers
     */
    public function setHeaders(?\PSX\Record\Record $headers): void
    {
        $this->headers = $headers;
    }
    /**
     * @return \PSX\Record\Record<string>|null
     */
    public function getHeaders(): ?\PSX\Record\Record
    {
        return $this->headers;
    }
    public function setRequireApproval(?string $requireApproval): void
    {
        $this->requireApproval = $requireApproval;
    }
    public function getRequireApproval(): ?string
    {
        return $this->requireApproval;
    }
    public function setServerDescription(?string $serverDescription): void
    {
        $this->serverDescription = $serverDescription;
    }
    public function getServerDescription(): ?string
    {
        return $this->serverDescription;
    }
    public function setServerUrl(?string $serverUrl): void
    {
        $this->serverUrl = $serverUrl;
    }
    public function getServerUrl(): ?string
    {
        return $this->serverUrl;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('server_label', $this->serverLabel);
        $record->put('type', $this->type);
        $record->put('allowed_tools', $this->allowedTools);
        $record->put('authorization', $this->authorization);
        $record->put('connector_id', $this->connectorId);
        $record->put('headers', $this->headers);
        $record->put('require_approval', $this->requireApproval);
        $record->put('server_description', $this->serverDescription);
        $record->put('server_url', $this->serverUrl);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
