<?php
/**
 * ResponseRequestInputMcpListTools automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;
use PSX\Schema\Attribute\Nullable;

#[Description('A list of tools available on an MCP server.')]
class ResponseRequestInputMcpListTools extends ResponseRequestInput implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The unique ID of the list.')]
    #[Nullable(true)]
    protected ?string $id = null;
    #[Key('server_label')]
    #[Description('The label of the MCP server.')]
    #[Nullable(true)]
    protected ?string $serverLabel = null;
    #[Description('The tools available on the server.')]
    #[Nullable(true)]
    protected ?string $tools = null;
    /**
     * @var array<ResponseMCPTool>|null
     */
    #[Description('The type of the item. Always mcp_list_tools.')]
    #[Nullable(true)]
    protected ?array $type = null;
    #[Description('Error message if the server could not list tools.')]
    #[Nullable(true)]
    protected ?string $error = null;
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setServerLabel(?string $serverLabel): void
    {
        $this->serverLabel = $serverLabel;
    }
    public function getServerLabel(): ?string
    {
        return $this->serverLabel;
    }
    public function setTools(?string $tools): void
    {
        $this->tools = $tools;
    }
    public function getTools(): ?string
    {
        return $this->tools;
    }
    /**
     * @param array<ResponseMCPTool>|null $type
     */
    public function setType(?array $type): void
    {
        $this->type = $type;
    }
    /**
     * @return array<ResponseMCPTool>|null
     */
    public function getType(): ?array
    {
        return $this->type;
    }
    public function setError(?string $error): void
    {
        $this->error = $error;
    }
    public function getError(): ?string
    {
        return $this->error;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('id', $this->id);
        $record->put('server_label', $this->serverLabel);
        $record->put('tools', $this->tools);
        $record->put('type', $this->type);
        $record->put('error', $this->error);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
