<?php
/**
 * ResponseRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseRequest implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Whether to run the model response in the background.')]
    protected ?bool $background = null;
    #[Description('The conversation that this response belongs to. Items from this conversation are prepended to input_items for this response request. Input items and output items from this response are automatically added to this conversation after this response completes.')]
    #[Nullable(true)]
    protected ?string $conversation = null;
    /**
     * @var array<string>|null
     */
    #[Description('Specify additional output data to include in the model response.')]
    protected ?array $include = null;
    /**
     * @var array<ResponseRequestInput>|null
     */
    #[Description('Text, image, or file inputs to the model, used to generate a response.')]
    #[Nullable(true)]
    protected ?array $input = null;
    #[Description('A system (or developer) message inserted into the model\'s context.  When using along with previous_response_id, the instructions from a previous response will not be carried over to the next response. This makes it simple to swap out system (or developer) messages in new responses.')]
    protected ?string $instructions = null;
    #[Key('max_output_tokens')]
    #[Description('An upper bound for the number of tokens that can be generated for a response, including visible output tokens and reasoning tokens.')]
    protected ?string $maxOutputTokens = null;
    #[Key('max_tool_calls')]
    #[Description('The maximum number of total calls to built-in tools that can be processed in a response. This maximum number applies across all built-in tool calls, not per individual tool. Any further attempts to call a tool by the model will be ignored.')]
    protected ?string $maxToolCalls = null;
    /**
     * @var \PSX\Record\Record<string>|null
     */
    #[Description('Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard.  Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters.')]
    protected ?\PSX\Record\Record $metadata = null;
    #[Description('Model ID used to generate the response, like gpt-4o or o3. OpenAI offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the model guide to browse and compare available models.')]
    protected ?string $model = null;
    #[Key('parallel_tool_calls')]
    #[Description('Whether to allow the model to run tool calls in parallel.')]
    protected ?bool $parallelToolCalls = null;
    #[Key('previous_response_id')]
    #[Description('The unique ID of the previous response to the model. Use this to create multi-turn conversations. Learn more about conversation state. Cannot be used in conjunction with conversation.')]
    protected ?string $previousResponseId = null;
    #[Description('Reference to a prompt template and its variables.')]
    protected ?ResponsePrompt $prompt = null;
    #[Key('prompt_cache_key')]
    #[Description('Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the user field.')]
    protected ?string $promptCacheKey = null;
    #[Description('gpt-5 and o-series models only')]
    protected ?ResponseReasoning $reasoning = null;
    #[Key('safety_identifier')]
    #[Description('A stable identifier used to help detect users of your application that may be violating OpenAI\'s usage policies. The IDs should be a string that uniquely identifies each user. We recommend hashing their username or email address, in order to avoid sending us any identifying information.')]
    protected ?string $safetyIdentifier = null;
    #[Key('service_tier')]
    #[Description('Specifies the processing type used for serving the request.')]
    protected ?string $serviceTier = null;
    #[Description('Whether to store the generated model response for later retrieval via API.')]
    protected ?bool $store = null;
    #[Description('What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.')]
    protected ?float $temperature = null;
    #[Description('Configuration options for a text response from the model. Can be plain text or structured JSON data.')]
    #[Nullable(true)]
    protected ?ResponseRequestText $text = null;
    #[Key('tool_choice')]
    #[Description('How the model should select which tool (or tools) to use when generating a response. See the tools parameter to see how to specify which tools the model can call.')]
    protected ?string $toolChoice = null;
    /**
     * @var array<ResponseRequestTool>|null
     */
    #[Description('An array of tools the model may call while generating a response. You can specify which tool to use by setting the tool_choice parameter.')]
    #[Nullable(true)]
    protected ?array $tools = null;
    #[Key('top_logprobs')]
    #[Description('An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability.')]
    protected ?int $topLogprobs = null;
    #[Key('top_p')]
    #[Description('An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or temperature but not both.')]
    protected ?float $topP = null;
    #[Description('The truncation strategy to use for the model response.')]
    protected ?string $truncation = null;
    public function setBackground(?bool $background): void
    {
        $this->background = $background;
    }
    public function getBackground(): ?bool
    {
        return $this->background;
    }
    public function setConversation(?string $conversation): void
    {
        $this->conversation = $conversation;
    }
    public function getConversation(): ?string
    {
        return $this->conversation;
    }
    /**
     * @param array<string>|null $include
     */
    public function setInclude(?array $include): void
    {
        $this->include = $include;
    }
    /**
     * @return array<string>|null
     */
    public function getInclude(): ?array
    {
        return $this->include;
    }
    /**
     * @param array<ResponseRequestInput>|null $input
     */
    public function setInput(?array $input): void
    {
        $this->input = $input;
    }
    /**
     * @return array<ResponseRequestInput>|null
     */
    public function getInput(): ?array
    {
        return $this->input;
    }
    public function setInstructions(?string $instructions): void
    {
        $this->instructions = $instructions;
    }
    public function getInstructions(): ?string
    {
        return $this->instructions;
    }
    public function setMaxOutputTokens(?string $maxOutputTokens): void
    {
        $this->maxOutputTokens = $maxOutputTokens;
    }
    public function getMaxOutputTokens(): ?string
    {
        return $this->maxOutputTokens;
    }
    public function setMaxToolCalls(?string $maxToolCalls): void
    {
        $this->maxToolCalls = $maxToolCalls;
    }
    public function getMaxToolCalls(): ?string
    {
        return $this->maxToolCalls;
    }
    /**
     * @param \PSX\Record\Record<string>|null $metadata
     */
    public function setMetadata(?\PSX\Record\Record $metadata): void
    {
        $this->metadata = $metadata;
    }
    /**
     * @return \PSX\Record\Record<string>|null
     */
    public function getMetadata(): ?\PSX\Record\Record
    {
        return $this->metadata;
    }
    public function setModel(?string $model): void
    {
        $this->model = $model;
    }
    public function getModel(): ?string
    {
        return $this->model;
    }
    public function setParallelToolCalls(?bool $parallelToolCalls): void
    {
        $this->parallelToolCalls = $parallelToolCalls;
    }
    public function getParallelToolCalls(): ?bool
    {
        return $this->parallelToolCalls;
    }
    public function setPreviousResponseId(?string $previousResponseId): void
    {
        $this->previousResponseId = $previousResponseId;
    }
    public function getPreviousResponseId(): ?string
    {
        return $this->previousResponseId;
    }
    public function setPrompt(?ResponsePrompt $prompt): void
    {
        $this->prompt = $prompt;
    }
    public function getPrompt(): ?ResponsePrompt
    {
        return $this->prompt;
    }
    public function setPromptCacheKey(?string $promptCacheKey): void
    {
        $this->promptCacheKey = $promptCacheKey;
    }
    public function getPromptCacheKey(): ?string
    {
        return $this->promptCacheKey;
    }
    public function setReasoning(?ResponseReasoning $reasoning): void
    {
        $this->reasoning = $reasoning;
    }
    public function getReasoning(): ?ResponseReasoning
    {
        return $this->reasoning;
    }
    public function setSafetyIdentifier(?string $safetyIdentifier): void
    {
        $this->safetyIdentifier = $safetyIdentifier;
    }
    public function getSafetyIdentifier(): ?string
    {
        return $this->safetyIdentifier;
    }
    public function setServiceTier(?string $serviceTier): void
    {
        $this->serviceTier = $serviceTier;
    }
    public function getServiceTier(): ?string
    {
        return $this->serviceTier;
    }
    public function setStore(?bool $store): void
    {
        $this->store = $store;
    }
    public function getStore(): ?bool
    {
        return $this->store;
    }
    public function setTemperature(?float $temperature): void
    {
        $this->temperature = $temperature;
    }
    public function getTemperature(): ?float
    {
        return $this->temperature;
    }
    public function setText(?ResponseRequestText $text): void
    {
        $this->text = $text;
    }
    public function getText(): ?ResponseRequestText
    {
        return $this->text;
    }
    public function setToolChoice(?string $toolChoice): void
    {
        $this->toolChoice = $toolChoice;
    }
    public function getToolChoice(): ?string
    {
        return $this->toolChoice;
    }
    /**
     * @param array<ResponseRequestTool>|null $tools
     */
    public function setTools(?array $tools): void
    {
        $this->tools = $tools;
    }
    /**
     * @return array<ResponseRequestTool>|null
     */
    public function getTools(): ?array
    {
        return $this->tools;
    }
    public function setTopLogprobs(?int $topLogprobs): void
    {
        $this->topLogprobs = $topLogprobs;
    }
    public function getTopLogprobs(): ?int
    {
        return $this->topLogprobs;
    }
    public function setTopP(?float $topP): void
    {
        $this->topP = $topP;
    }
    public function getTopP(): ?float
    {
        return $this->topP;
    }
    public function setTruncation(?string $truncation): void
    {
        $this->truncation = $truncation;
    }
    public function getTruncation(): ?string
    {
        return $this->truncation;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('background', $this->background);
        $record->put('conversation', $this->conversation);
        $record->put('include', $this->include);
        $record->put('input', $this->input);
        $record->put('instructions', $this->instructions);
        $record->put('max_output_tokens', $this->maxOutputTokens);
        $record->put('max_tool_calls', $this->maxToolCalls);
        $record->put('metadata', $this->metadata);
        $record->put('model', $this->model);
        $record->put('parallel_tool_calls', $this->parallelToolCalls);
        $record->put('previous_response_id', $this->previousResponseId);
        $record->put('prompt', $this->prompt);
        $record->put('prompt_cache_key', $this->promptCacheKey);
        $record->put('reasoning', $this->reasoning);
        $record->put('safety_identifier', $this->safetyIdentifier);
        $record->put('service_tier', $this->serviceTier);
        $record->put('store', $this->store);
        $record->put('temperature', $this->temperature);
        $record->put('text', $this->text);
        $record->put('tool_choice', $this->toolChoice);
        $record->put('tools', $this->tools);
        $record->put('top_logprobs', $this->topLogprobs);
        $record->put('top_p', $this->topP);
        $record->put('truncation', $this->truncation);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
