<?php
/**
 * ResponseToolWebSearchLocation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ResponseToolWebSearchLocation implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Free text input for the city of the user, e.g. San Francisco.')]
    protected ?string $city = null;
    #[Description('The two-letter ISO country code of the user, e.g. US.')]
    protected ?string $country = null;
    #[Description('Free text input for the region of the user, e.g. California.')]
    protected ?string $region = null;
    #[Description('The IANA timezone of the user, e.g. America/Los_Angeles.')]
    protected ?string $timezone = null;
    #[Description('The type of location approximation. Always approximate.')]
    protected ?string $type = null;
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }
    public function getCity(): ?string
    {
        return $this->city;
    }
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }
    public function getCountry(): ?string
    {
        return $this->country;
    }
    public function setRegion(?string $region): void
    {
        $this->region = $region;
    }
    public function getRegion(): ?string
    {
        return $this->region;
    }
    public function setTimezone(?string $timezone): void
    {
        $this->timezone = $timezone;
    }
    public function getTimezone(): ?string
    {
        return $this->timezone;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('city', $this->city);
        $record->put('country', $this->country);
        $record->put('region', $this->region);
        $record->put('timezone', $this->timezone);
        $record->put('type', $this->type);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
