<?php
/**
 * ResponseRequestInputMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseRequestInputMessage extends ResponseRequestInput implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Text, image, or audio input to the model, used to generate a response. Can also contain previous assistant responses.')]
    #[Nullable(true)]
    protected ?string $content = null;
    #[Description('The role of the message input. One of user, assistant, system, or developer.')]
    #[Nullable(true)]
    protected ?string $role = null;
    #[Description('The type of the message input. Always message.')]
    #[Nullable(true)]
    protected ?string $type = 'message';
    public function setContent(?string $content): void
    {
        $this->content = $content;
    }
    public function getContent(): ?string
    {
        return $this->content;
    }
    public function setRole(?string $role): void
    {
        $this->role = $role;
    }
    public function getRole(): ?string
    {
        return $this->role;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('content', $this->content);
        $record->put('role', $this->role);
        $record->put('type', $this->type);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
