<?php
/**
 * ResponseRequestInputFunctionCallOutput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;
use PSX\Schema\Attribute\Nullable;

#[Description('The output of a function tool call.')]
class ResponseRequestInputFunctionCallOutput extends ResponseRequestInput implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('call_id')]
    #[Description('The unique ID of the function tool call generated by the model.')]
    #[Nullable(true)]
    protected ?string $callId = null;
    #[Description('Text, image, or file output of the function tool call.')]
    #[Nullable(true)]
    protected ?string $output = null;
    #[Description('The type of the function tool call output. Always function_call_output.')]
    #[Nullable(true)]
    protected ?string $type = 'function_call_output';
    #[Description('The unique ID of the function tool call output. Populated when this item is returned via API.')]
    #[Nullable(true)]
    protected ?string $id = null;
    #[Description('The status of the item. One of in_progress, completed, or incomplete. Populated when items are returned via API.')]
    #[Nullable(true)]
    protected ?string $status = null;
    public function setCallId(?string $callId): void
    {
        $this->callId = $callId;
    }
    public function getCallId(): ?string
    {
        return $this->callId;
    }
    public function setOutput(?string $output): void
    {
        $this->output = $output;
    }
    public function getOutput(): ?string
    {
        return $this->output;
    }
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }
    public function getStatus(): ?string
    {
        return $this->status;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('call_id', $this->callId);
        $record->put('output', $this->output);
        $record->put('type', $this->type);
        $record->put('id', $this->id);
        $record->put('status', $this->status);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
