<?php
/**
 * ResponseToolWebSearch automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseToolWebSearch extends ResponseTool implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The type of the web search tool. One of web_search or web_search_2025_08_26.')]
    #[Nullable(true)]
    protected ?string $type = 'web_search';
    #[Description('Filters for the search.')]
    protected ?ResponseToolWebSearchFilter $filters = null;
    #[Key('search_context_size')]
    #[Description('High level guidance for the amount of context window space to use for the search. One of low, medium, or high. medium is the default.')]
    protected ?string $searchContextSize = null;
    #[Key('user_location')]
    #[Description('The approximate location of the user.')]
    protected ?ResponseToolWebSearchLocation $userLocation = null;
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function setFilters(?ResponseToolWebSearchFilter $filters): void
    {
        $this->filters = $filters;
    }
    public function getFilters(): ?ResponseToolWebSearchFilter
    {
        return $this->filters;
    }
    public function setSearchContextSize(?string $searchContextSize): void
    {
        $this->searchContextSize = $searchContextSize;
    }
    public function getSearchContextSize(): ?string
    {
        return $this->searchContextSize;
    }
    public function setUserLocation(?ResponseToolWebSearchLocation $userLocation): void
    {
        $this->userLocation = $userLocation;
    }
    public function getUserLocation(): ?ResponseToolWebSearchLocation
    {
        return $this->userLocation;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('type', $this->type);
        $record->put('filters', $this->filters);
        $record->put('search_context_size', $this->searchContextSize);
        $record->put('user_location', $this->userLocation);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
