<?php
/**
 * ResponsePrompt automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ResponsePrompt implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The unique identifier of the prompt template to use.')]
    protected ?string $id = null;
    /**
     * @var \PSX\Record\Record<string>|null
     */
    #[Description('Optional map of values to substitute in for variables in your prompt. The substitution values can either be strings, or other Response input types like images or files.')]
    protected ?\PSX\Record\Record $variables = null;
    #[Description('Optional version of the prompt template.')]
    protected ?string $version = null;
    public function setId(?string $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?string
    {
        return $this->id;
    }
    /**
     * @param \PSX\Record\Record<string>|null $variables
     */
    public function setVariables(?\PSX\Record\Record $variables): void
    {
        $this->variables = $variables;
    }
    /**
     * @return \PSX\Record\Record<string>|null
     */
    public function getVariables(): ?\PSX\Record\Record
    {
        return $this->variables;
    }
    public function setVersion(?string $version): void
    {
        $this->version = $version;
    }
    public function getVersion(): ?string
    {
        return $this->version;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('id', $this->id);
        $record->put('variables', $this->variables);
        $record->put('version', $this->version);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
