<?php
/**
 * ResponseRequestInput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\DerivedType;
use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Discriminator;
use PSX\Schema\Attribute\Nullable;

#[Description('An item representing part of the context for the response to be generated by the model. Can contain text, images, and audio inputs, as well as previous assistant responses and tool call outputs.')]
#[Discriminator('type')]
#[DerivedType(ResponseRequestInputFunctionCall::class, 'function_call')]
#[DerivedType(ResponseRequestInputFunctionCallOutput::class, 'function_call_output')]
#[DerivedType(ResponseRequestInputMessage::class, 'message')]
abstract class ResponseRequestInput implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    #[Nullable(true)]
    protected ?string $type = null;
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('type', $this->type);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
