<?php
/**
 * ResponseMCPTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Key;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseMCPTool implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Key('input_schema')]
    #[Description('The JSON schema describing the tool\'s input.')]
    #[Nullable(true)]
    protected mixed $inputSchema = null;
    #[Description('The name of the tool.')]
    #[Nullable(true)]
    protected ?string $name = null;
    /**
     * @var \PSX\Record\Record<string>|null
     */
    #[Description('Additional annotations about the tool.')]
    #[Nullable(true)]
    protected ?\PSX\Record\Record $annotations = null;
    #[Description('The description of the tool.')]
    #[Nullable(true)]
    protected ?string $description = null;
    public function setInputSchema(mixed $inputSchema): void
    {
        $this->inputSchema = $inputSchema;
    }
    public function getInputSchema(): mixed
    {
        return $this->inputSchema;
    }
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    /**
     * @param \PSX\Record\Record<string>|null $annotations
     */
    public function setAnnotations(?\PSX\Record\Record $annotations): void
    {
        $this->annotations = $annotations;
    }
    /**
     * @return \PSX\Record\Record<string>|null
     */
    public function getAnnotations(): ?\PSX\Record\Record
    {
        return $this->annotations;
    }
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('input_schema', $this->inputSchema);
        $record->put('name', $this->name);
        $record->put('annotations', $this->annotations);
        $record->put('description', $this->description);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
