<?php
/**
 * ResponseRequestTextFormatText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;
use PSX\Schema\Attribute\Nullable;

#[Description('')]
class ResponseRequestTextFormatText extends ResponseRequestTextFormat implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The type of response format being defined. Always text.')]
    #[Nullable(true)]
    protected ?string $type = 'text';
    public function setType(?string $type): void
    {
        $this->type = $type;
    }
    public function getType(): ?string
    {
        return $this->type;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('type', $this->type);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
