<?php
/**
 * ResponseReasoning automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace SdkFabric\Openai;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ResponseReasoning implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Constrains effort on reasoning for reasoning models. Currently supported values are minimal, low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.  Note: The gpt-5-pro model defaults to (and only supports) high reasoning effort.')]
    protected ?string $effort = null;
    #[Description('A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model\'s reasoning process. One of auto, concise, or detailed.')]
    protected ?string $summary = null;
    public function setEffort(?string $effort): void
    {
        $this->effort = $effort;
    }
    public function getEffort(): ?string
    {
        return $this->effort;
    }
    public function setSummary(?string $summary): void
    {
        $this->summary = $summary;
    }
    public function getSummary(): ?string
    {
        return $this->summary;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('effort', $this->effort);
        $record->put('summary', $this->summary);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
